"""Slack notifier — sends the job report to a Slack channel via Incoming Webhook."""

import logging
from collections import defaultdict
from datetime import date

import httpx

logger = logging.getLogger(__name__)


def send_slack_report(ml_jobs: list[dict], webhook_url: str) -> None:
    today = date.today().isoformat()

    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": "Engineer Upsale Opportunities"}},
        {"type": "context", "elements": [{"type": "mrkdwn", "text": f"*Date:* {today}"}]},
        {"type": "divider"},
    ]

    if not ml_jobs:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": "_No new engineer upsale opportunities detected today._"},
        })
    else:
        by_company: dict[str, list[dict]] = defaultdict(list)
        for job in ml_jobs:
            by_company[job["company_name"]].append(job)

        for company, jobs in by_company.items():
            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*{company}*"},
            })
            lines = []
            for job in jobs:
                title = job.get("title", "")
                url = job.get("url", "")
                posted = job.get("posted_date", "")
                description = job.get("description", "")

                line = f"• <{url}|{title}>" if url else f"• {title}"
                line += f" — {posted}"
                if description:
                    line += f"\n  _{description}_"
                lines.append(line)

            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": "\n".join(lines)},
            })

    blocks += [
        {"type": "divider"},
        {"type": "context", "elements": [{"type": "mrkdwn", "text": "_Generated by Job Monitor Agent_"}]},
    ]

    response = httpx.post(webhook_url, json={"blocks": blocks}, timeout=10)
    response.raise_for_status()
    logger.info("Slack report sent")
