from collections import defaultdict
from datetime import date
from pathlib import Path


def generate_report(ml_jobs: list[dict]) -> str:
    today = date.today().isoformat()
    lines = [f"# Engineer Upsale Opportunities", f"**Date:** {today}", ""]

    if not ml_jobs:
        lines.append("_No new engineer upsale opportunities detected today._")
    else:
        by_company = defaultdict(list)
        for job in ml_jobs:
            by_company[job["company_name"]].append(job)

        for company, jobs in by_company.items():
            lines.append(f"## {company}")
            for job in jobs:
                title = job.get("title", "")
                url = job.get("url", "")
                posted = job.get("posted_date", "")
                description = job.get("description", "")

                if url:
                    lines.append(f"- [{title}]({url}) — {posted}")
                else:
                    lines.append(f"- {title} — {posted}")

                if description:
                    lines.append(f"  {description}")
            lines.append("")

    lines += ["---", "_Generated by Job Monitor Agent_"]
    report = "\n".join(lines)

    reports_dir = Path(__file__).parent / "reports"
    reports_dir.mkdir(exist_ok=True)
    report_path = reports_dir / f"{today}_report.md"
    report_path.write_text(report)

    print(report)
    return report
